# Generated by Django 2.2 on 2019-07-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('publish_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('url', models.URLField(verbose_name='Ссылка на новость')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
